# volcano create patch from 'main' branch
name: action patch
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'prod'
          token: ${{ secrets.VOLCANO_GITHUB_TOKEN }}

      - name: setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: patch
        run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name  'github-actions[bot]'
          git fetch --all
          git checkout main
          npm version patch
          git branch -f prod
          git push origin main prod --tags